### ISSUE TITLE
Create api calls for Versions and any other metadata

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/InitializrApi#16]

**Comment by jkonicki** [comment]
This work was completed with InitializrApi split.  Just need to be validated.

**Comment by ccheetham** [comment]
Needs to be reimpl'd per rewriting of endpoint logic.

Required endpoints:

- [ ] /api/config/steeltoeVersions
- [ ] /api/config/dotnetFrameworks
- [ ] /api/config/dotnetTemplates
- [ ] /api/config/languages
- [ ] /api/config/archiveTypes
- [ ] /api/config/dependencies
