### ISSUE TITLE
Add support for CORS origins

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/InitializrApi#36]
Web client apps, such as the InitializrWeb project, may need to forward requests to API server while honoring CORS policies.

see: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

The InitializrApi needs to set the `Access-Control-Allow-Origin` header so that client can access its resources.

**Comment by jkonicki** [comment]
We want to be able to lock this down just to our client.
