### ISSUE TITLE
Add the analytics back for dependencies

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/InitializrApi#65]
Add the analytics back for selections.

**Comment by ccheetham** [comment]
Google Analytics Measurement API docs:
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide

**Comment by ccheetham** [comment]
Sample collection using tags: https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Management/src/EndpointBase/Metrics/Observer/CLRRuntimeObserver.cs
