### ISSUE TITLE
Investigate template engine options

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/InitializrApi#71]
Currently Initializr uses the Stubble implementation of Mustache for the template engine.  The team should gather all of our requirements for the template engine and look into what is the best template option moving forward (e.g. dotnet templating, stubble, mustache, DIY, etc.)

**Comment by ccheetham** [comment]
After a couple prototypes, it seems best path forward to is port templates to the .NET templating framework (i.e., `dotnet new ...`).

Benefits:
* templates are compilable, making them easier to develop/test
* framework is part of .NET ecosystem, making easier for community to contribute
