### ISSUE TITLE
unknown dependency should return a 404

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/InitializrApi#79]
If an unknown dependency is requested, a 404 should be returned.  Instead API is return a 200.

```
$ http https://start.steeltoe.io/api/project dependencies==nosuchdep
HTTP/1.1 200 OK
...
```

**Comment by ccheetham** [comment]
@ddieruf this should address a portion of the lack of API feedback

**Comment by ddieruf** [comment]
So given your comments on my other issue and the subject of this, is it your opinion that the API should return 4xx codes in all scenarios where the provided payload doesn't run/match perfectly?

**Comment by ccheetham** [comment]
There is standard recommendation of what to do with unknown parameters in REST APIs.  Common practice is to ignore them, yet there are examples where some type of 4xx is returned.

For Steeltoe Initializer, the intent was to follow Spring Initializr (return 200).  

Here are examples of Spring's behavior in the 2 scenarios germane to this issue:
```
http https://start.spring.io/starter.zip dependencies==nosuchdep
HTTP/1.1 404
...
http https://start.spring.io/starter.zip nosuchparam==nosuchdep
HTTP/1.1 200
...
```

**Comment by ddieruf** [comment]
When I look at this through the lens of automation that 200 for nosuchparam is not ideal. If that was a simple type-o it could be the type of thing that you spend hours debugging. But I do understand following Spring's patterns.

**Comment by ccheetham** [comment]
Sample behavior:
```
$ http https://start-staging.steeltoe.io/api/project dependencies==foo
HTTP/1.1 404 Not Found
...

Dependency 'foo' not found.
```
